config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length:{ minimum:3, maximum: 15}, uniqueness: { case_sensitive: false}
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||=User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error]="you must be log in"
            redirect_to login_path
        end
    end

end

app/controllers/chatroom_controller.rb
class ChatroomController<ApplicationController
	before_action :require_user
	def index
		@message = Message.new
		@messages = Message.preload(:user)
	end

end

app/controllers/messages_controller.rb
class MessagesController<ApplicationController
    
    before_action :require_user
    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", foo: message.body
        end
    end
    private

    def message_params
        params.require(:message).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController
	before_action :logged_in_redirect, only: [:new, :create]
	def new

	end
	def create
	user = User.find_by(username: params[:session][:username])
	if user
		session[:user_id] = user.id
		redirect_to root_path
	else
		render 'new'
	end
	end

	def destroy
		session[:user_id] = nil
		
		redirect_to login_path
	end
	private
	def logged_in_redirect
		if logged_in?
			flash[:error] = "already logged in"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<center><p>chatroom</p></center>

<br>
<% @messages.each do |message| %>
    <p><%= message.user.username %> : <%= message.body %></p>
<% end %>

<%= form_for(@message, url: message_path) do |f| %>
    <%= f.text_field :body %>
    <%= f.button %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messageapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <center>
    <% if logged_in? %>
      <%= link_to "logout", logout_path, method: :delete %>

    <% else %>
      <%= link_to "log in", login_path %>

    <% end %>
    </center>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>